import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshiFont = localFont({
  src: "../fonts/Satoshi-Variable.ttf"
});

export const metadata: Metadata = {
  title: "Shoes Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshiFont.className} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
